### ISSUE TITLE
[失效] 会议记录

### ISSUE THREAD

**Issue by EchoCxt** [BeaverTeam/BeaverMovie#1]
## 第一次会议思维导图
看看有没有什么需要改动的
![5](https://cloud.githubusercontent.com/assets/21984638/24129197/e348cda8-0e1b-11e7-8163-ef1be089f270.png)

**Comment by An0nym6** [comment]
我觉得我们应该在会议结果方案的辅助亮点中添加 **“简约风设计”** 这一条，对应着问题分析中的 **“现在网站存在内容繁杂的缺点”** 。

按照潘老师上课的意思，他要我们实现的是一个虚拟、完整的售票系统，包括付款甚至院线的排片，我们最开始讨论的 **“跳转到价格最低的平台完成购票”** 可能不契合要求，我们下次开会的时候应该重新讨论讨论产品的设计和亮点 orz。
