### ISSUE TITLE
[失效] 成员职务初定、项目启动文档分工

### ISSUE THREAD

**Issue by shuq3** [BeaverTeam/BeaverMovie#2]
## 成员职务

| 职务 | 姓名 |
| - | - |
| 项目经理 | 陈昕彤 |
| 客户经理 | 梁晓婷 |
| 配置经理 | 符宇晖 |
| 质量保证经理 | 刘忍 |
| 测试工程师 | 钟正 |
| 技术经理 | 舒倩 |

## 项目启动文档分工

| 分工 | 姓名 |
| - | - |
| 调查报告设计和数据分析 | 梁晓婷 |
| 调查报告数据收集 | 所有人 |
| 第一次会议纪要 | 陈昕彤 |
| 团队信息 | 陈昕彤 |
| 项目愿景 | 刘忍、舒倩 |
| 产品特性 | 陈昕彤 |

## 个人宣言

| 姓名 | 个人宣言 |
| - | - |
| 刘忍 | 为了防止世界被破坏 |
| 舒倩 | 为了维护世界的和平 |
| 梁晓婷 | 贯彻爱与真实的应用 |
| 钟正 | 可爱又迷人的 coder |
| 陈昕彤 | 白洞，白色的明天在等着我们 |
| 符宇晖 | 就是这样......喵 |

**Comment by An0nym6** [comment]
## 项目第二波文档分工

| 分工 | 姓名 |
| - | - |
| sprint paln | 钟正 |
| use case | 舒倩、陈昕彤 |
| code style、tech overview、env report | 刘忍、符宇晖 |
