### ISSUE TITLE
[失效] 后端需提供的 API

### ISSUE THREAD

**Issue by shuq3** [BeaverTeam/BeaverMovie#8]
## 认证 API

| URL | 方法 | 参数 | 返回值 | 说明 |
| - | - | - | - | - |
| /api/sign-up | POST | { username: string, encryptedPassword: string } | { success: boolean, userId: number } | 上传用户名和 MD5 哈希过的密码（用户名和密码已通过前端校验，后端还需对用户名和加密后的密码进行校验），后端根据参数创建一个新的用户 |
| /api/sign-in | POST | { username: string, encryptedPassword: string } | { success: boolean, userId: number } | 同上，后端判断该用户是否合法，合法则返回 session |
| /api/sign-out | GET | session 带在 headers 里，无参数 | { success: boolean, userId: number } | 后端判断该用户是否合法，合法则过期掉 session |

**其他 API：** 当访问限制级数据时需要附上 session，后端根据 session 判断用户的合法性。

**Comment by tonitick** [comment]
小灰灰代码返回值里面第二个参数好像是个整数的样子...我就按着他的写啦

**Comment by An0nym6** [comment]
@tonitick 嗯，不影响。我觉得小灰灰之前说的后端不给错有道理，我改了上面的 API。
